"""
gen_build_secrets.py  -  generate per-build random salt + payload IV
for the AES payload encryption pipeline.

Run BEFORE building the loader.  The vcxproj pre-build step invokes
this automatically if build_secrets.h is missing.

Output: build_secrets.h (gitignored  -  each build has unique values).
"""

import os
import secrets
import sys

OUT_FILE = "build_secrets.h"


def fmt_bytes(name, b):
    rows = []
    for i in range(0, len(b), 8):
        chunk = b[i:i + 8]
        line = ", ".join(f"0x{x:02X}" for x in chunk)
        if i + 8 < len(b):
            line += ","
        rows.append("    " + line)
    body = "\n".join(rows)
    return f"static constexpr unsigned char {name}[] = {{\n{body}\n}};\n"


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    out_path = os.path.join(here, OUT_FILE)

    salt = secrets.token_bytes(32)
    iv   = secrets.token_bytes(16)

    text = (
        "#pragma once\n"
        "\n"
        "// AUTO-GENERATED by gen_build_secrets.py.\n"
        "// Each build has unique values.  Do not commit.\n"
        "\n"
    )
    text += fmt_bytes("kBuildSalt", salt)
    text += "\n"
    text += fmt_bytes("kPayloadIV", iv)

    with open(out_path, "w") as f:
        f.write(text)

    print(f"Wrote {OUT_FILE}: salt[0..3]={salt[:4].hex()}, iv[0..3]={iv[:4].hex()}")


if __name__ == "__main__":
    sys.exit(main() or 0)
